name: all_data
working_directory: /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data
steps:
#  - Annotations
#  - Collate
#  - Partition
  - MakeDataset
#  - Train+Test
#  - Summarize
datasets:
  - /dls/labxchem/data/*/*/processing/analysis/*
  - /dls/labxchem/data/*/*/processing/analysis/pandda_2_2023_06_27/1
  - /dls/labxchem/data/lb32633/lb32633-1/processing/analysis/pandda_2_2023_08_22/pandda
  - /dls/labxchem/data/lb32627/lb32627-22/processing/analysis/pandda_2_2023_08_17/pandda
exclude:
  - /dls/labxchem/data/*/i*/processing/analysis/*
  - /dls/labxchem/data/*/s*/processing/analysis/*
  - /dls/labxchem/data/*/n*/processing/analysis/*
train:
  max_epochs: 200
  model_file:
test:
  test_interval: 1
  test_convergence_interval: 10
  partition: pandda_2_5
  source: pandda_2
custom_annotations: /dls/science/groups/i04-1/conor_dev/edanalyzer/test/database.db
cpus: 36
