name: all_data
working_directory: /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data_2
steps:
#  - Annotations
#  - Collate
#  - Partition
#  - MakeTestDatasetPsuedoPanDDA
  - MakeReannotationPsuedoPanDDA
#  - KnownHitAlternateModel
#  - MakeDataset
#  - Train+Test
#  - Summarize
datasets:
  - /dls/labxchem/data/*/*/processing/analysis/*
  - /dls/labxchem/data/*/*/processing/analysis/pandda_2_2023_06_27/1
  - /dls/labxchem/data/*/*/processing/analysis/pandda_2_2023_09_04/1
  - /dls/labxchem/data/lb32633/lb32633-1/processing/analysis/pandda_2_2023_08_22/pandda
  - /dls/labxchem/data/lb32627/lb32627-22/processing/analysis/pandda_2_2023_08_17/pandda
  - /dls/science/groups/i04-1/conor_dev/baz2b_test/BAZ2BA_6
exclude:
  - /dls/labxchem/data/*/i*/processing/analysis/*
  - /dls/labxchem/data/*/s*/processing/analysis/*
  - /dls/labxchem/data/*/n*/processing/analysis/*
train:
  max_epochs: 200
#  model_file: /dls/science/groups/i04-1/conor_dev/pandda_2_gemmi/pandda_gemmi/cnn/model_ligand.pt
  model_file: /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data_2/all_data220.pt
test:
  initial_epoch: 60
  test_interval: 1
  test_convergence_interval: 10
  partition: pandda_2_5
  source: pandda_2
  test_systems:
    - MRE11AA
    - SETDB1
    - NSP15_B
    - BAZ2BA
custom_annotations:
  databases:
  - /dls/science/groups/i04-1/conor_dev/edanalyzer/test/database.db
  panddas:
  - /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data/lrh/low_ranking_hits_*
  - /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data/lrh/high_ranking_non_hits_*
  - /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data_2/high_ranking_non_hits/high_ranking_non_hits_*
  - /dls/science/groups/i04-1/conor_dev/edanalyzer/workspace_all_data_2/low_ranking_hits/low_ranking_hits_*
cpus: 20
